.TH kindle-cleaner 1 "Dec 24, 2016" "version 1.0"

.SH NAME
kindle-cleaner - Clean up the directory of Kindle

.SH SYNOPSIS
.B kindle-cleaner 
.RB [ " -h " |  " --help " ] 
.br
.RB "               [ " -n " | " --normal " ] "
.br
.RB "               [ " -s " | " --strict " ] "
.br
               [ 
.BI -p " PATH " 
|
.BI --path= PATH
]


.SH DESCRIPTION
Clean up the directory of Kindle, delete the unnecessary *.sdr file, free up the disk space of Kindle. To use this program, you should connect the Kindle to your computer using a micro-USB cable first.

.SH OPTIONS
.TP
.BR "-h" ", " "--help"
Show help message and exit
.TP
.BR "-n" ", " "--normal"
Normal mode, this mode is faster than the 
.IR "Strict mode" ,
but in some case, the effectiveness of this mode may not as good as
.IR "Strict mode" ". This mode is also the default mode."
.TP
.BR "s" ", " "--strict"
Strict mode
.LP
.BI -p
.IR PATH ,
.BI "--path=" "PATH"
       Specific the path of directory that you want to clean up. If you not use this option, the default directory is
.I /media/i-renyuntao/Kindle/documents 

.SH AUTHOR
Yuntao Ren 

.SH BUGS
Please send problems, bugs, questions, desirable enhancements to:
.I rytubuntulinux@gmail.com
